# Generated by Django 4.2.1 on 2023-06-22 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('cover_picture', models.ImageField(upload_to='media/hotel/hotel_covers/')),
                ('hotel_logo', models.ImageField(upload_to='media/hotel/hotel_logos/')),
                ('picture1', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('picture2', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('picture3', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('picture4', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('picture5', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('picture6', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('picture7', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('picture8', models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/')),
                ('has_pool', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_spa', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_conference_facilities', models.BooleanField(default=False)),
                ('has_room_service', models.BooleanField(default=False)),
                ('has_bar', models.BooleanField(default=False)),
                ('has_fitness_center', models.BooleanField(default=False)),
                ('has_business_center', models.BooleanField(default=False)),
                ('has_laundry_service', models.BooleanField(default=False)),
                ('has_childcare', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_hot_tub', models.BooleanField(default=False)),
                ('has_sauna', models.BooleanField(default=False)),
                ('has_24_hour_front_desk', models.BooleanField(default=False)),
                ('has_airport_shuttle', models.BooleanField(default=False)),
                ('has_car_rental', models.BooleanField(default=False)),
                ('has_currency_exchange', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('picture1', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('picture2', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('picture3', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('picture4', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('picture5', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('picture6', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('picture7', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('picture8', models.ImageField(blank=True, upload_to='media/room/room_pictures/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
