# Generated by Django 4.2.1 on 2023-06-24 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerthread',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
