# Generated by Django 4.2.1 on 2023-06-21 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cover_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/hotel/hotel_covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/hotel/hotel_logos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture1',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture2',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture3',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture4',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture5',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture6',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture7',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture8',
            field=models.ImageField(blank=True, upload_to='media/hotel/hotel_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture1',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture2',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture3',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture4',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture5',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture6',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture7',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture8',
            field=models.ImageField(blank=True, upload_to='media/room/room_pictures/'),
        ),
    ]
