# Generated by Django 4.2.1 on 2023-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomavailability',
            name='is_unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
