# Generated by Django 4.2.1 on 2023-06-22 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_cover_picture_hotel_hotel_logo_hotel_picture1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
