# Generated by Django 4.2.1 on 2023-06-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_booking_name_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
