# Generated by Django 4.2.1 on 2023-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_service_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='availability',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
