# Generated by Django 4.2.1 on 2023-06-18 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/service_covers/'),
            preserve_default=False,
        ),
    ]
